"""Matchup sheet schema, hand-written seed rows, and a read-only DB builder.

What this module actually does
------------------------------
1. Declares two documentation-only schemas, ``ARCHETYPE_PROFILE_SCHEMA`` and
   ``MATCHUP_SHEET_SCHEMA``. They are plain dicts describing the intended shape;
   nothing in this module generates them.
2. Ships three hand-written seed sheets (``SEED_SHEETS``) for ONE archetype key
   (``greninja`` / ``mega_greninja``). They are user notes typed 2026-09-07 and
   stay ``verified: false``; they were never checked against card text. They are
   only returned when the caller asks for that exact archetype, and every
   returned seed row carries a ``placeholder_note``.
3. Can derive a read-only matchup sheet from rows already stored in the
   ``format_archetype_briefs`` table (the ``profile`` JSONB written by
   ``services.limitless_decks.meta_field``). This path only *reads*: no DDL, no
   inserts, no network calls. Derived breakpoints compare stored printed attack
   damage against stored HP and ignore weakness / resistance / tools /
   abilities / cross-card combos, so they are always ``verified: false``.

What this module does NOT do
----------------------------
* There is no "nightly archetype profile" job. Nothing in this repository
  generates archetype profiles on a schedule; earlier revisions of this file
  claimed one. ``ARCHETYPE_PROFILE_SCHEMA`` is documentation only.
* It never invents cross-card kill lines and never substitutes another
  archetype's data. A missing or unknown ``user_archetype`` yields an explicit
  ``{"available": False, "reason": ..., "matchups": []}`` result instead of
  silently defaulting to an unrelated archetype.

``docs/MATCHUP_SHEET.md`` still describes the intended two-layer design and its
"每晚 batch" wording; treat that as aspirational, not implemented.

Public functions:
    get_matchup_sheet(user_archetype, opponent_archetype) -> dict
    list_matchup_sheets() -> list[dict]
"""

from __future__ import annotations

import re
from typing import Any


SCHEMA_VERSION = "2026-09-07.1"

# Honest description of where each layer's data comes from today.
GENERATION_NOTES: dict[str, str] = {
    "archetype_profile": "not_implemented",
    "archetype_profile_detail": (
        "倉庫內並無 nightly job 產生 archetype profile；"
        "ARCHETYPE_PROFILE_SCHEMA 只係文件用 schema。"
    ),
    "matchup_sheet": "on_request_read_only",
    "matchup_sheet_detail": (
        "聊天時即場讀 format_archetype_briefs 或者手寫種子，唯讀，唔會寫庫。"
    ),
    "seed_rows": "user_authored_placeholder_verified_false",
    "user_kill_lines": "not_implemented",
}

# Documentation-only schema for an archetype profile. Nothing generates this.
ARCHETYPE_PROFILE_SCHEMA = {
    "archetype_id": "slug",
    "display_name": "str",
    "updated_at": "ISO-8601",
    "source": ["limitless", "jp_tournament", "user_seed"],
    "setup": {
        "evolution_stage": "basic | stage1 | stage2 | mega | mixed",
        "energy_to_attack": "int",
        "energy_type": "str",
        "boost_cost": "str | null  # e.g. discard Water energy",
        "search_filter_notes": "str",
    },
    "quirks": [
        {
            "id": "slug",
            "rule": "str  # tera_bench_prevents_attack_damage",
            "applies_to": "active | bench | self | opponent",
            "note": "str",
        }
    ],
    "printed_lines": [
        {
            "card": "str",
            "kind": "attack | ability | item | tool",
            "damage": "int | null",
            "target": "active | bench | both | self",
            "cost": "str",
            "condition": "str",
        }
    ],
    "hp_table": [
        {"card": "str", "hp": "int", "notes": "str"}
    ],
}

# Documentation-only schema for one (user_deck x opponent_archetype) sheet.
MATCHUP_SHEET_SCHEMA = {
    "schema_version": SCHEMA_VERSION,
    "user_archetype": "str",
    "opponent_archetype": "str",
    "verified": "bool  # false unless numbers were checked against card rows",
    "setup": ARCHETYPE_PROFILE_SCHEMA["setup"],
    "quirks": ARCHETYPE_PROFILE_SCHEMA["quirks"],
    "breakpoints": [
        {
            "defender": "str",
            "hp": "int",
            "modifier": "none | chip | tool | ability",
            "modifier_note": "str",
            "effective_hp": "int",
            "killed_by": ["str"],
            "not_killed_by": ["str"],
        }
    ],
    "vs_archetype": {
        "advantages": ["str"],
        "disadvantages": ["str"],
        "kill_lines": ["str"],
        "tempo_note": "str",
    },
}


# Hand-written user notes (2026-09-07). ONE archetype only: greninja.
# These are NOT card-DB verified and are NOT generated by any profile job.
SEED_SHEETS: list[dict[str, Any]] = [
    {
        "schema_version": SCHEMA_VERSION,
        "user_archetype": "mega_greninja",
        "user_display_name": "Mega 水忍蛙／甲賀忍蛙",
        "opponent_archetype": "dragapult",
        "opponent_display_name": "多龍",
        "verified": False,
        "source": "user_seed_2026-09-07",
        "setup": {
            "evolution_stage": "stage2",
            "energy_to_attack": 2,
            "energy_type": "Water",
            "boost_cost": "加傷要棄水能量，能量需求再升，且要濾到那張能量",
            "search_filter_notes": "2 階展開本身慢，再加 2 能量同棄能加傷",
        },
        "quirks": [
            {
                "id": "tera_bench_block_attack",
                "rule": "太晶在備戰區可防止招式傷害",
                "applies_to": "bench",
                "note": "後排忍蛙唔驚多龍穿招式傷害；特性傷／放置指示物仍要另計",
            }
        ],
        "breakpoints": [
            {
                "defender": "甲賀忍蛙／Mega 水忍蛙",
                "hp": 310,
                "modifier": "none",
                "modifier_note": "原血",
                "effective_hp": 310,
                "killed_by": ["主攻 + 黑夜魔靈／夜巡靈特性自昏 130"],
                "not_killed_by": ["多數單招未加炸彈"],
            }
        ],
        "vs_archetype": {
            "advantages": [
                "太晶後排防多龍穿招式傷害",
                "水忍蛙可選 200 前排、後排 120x2、或 170 再選牌",
            ],
            "disadvantages": [
                "310 低過部分多龍線，加炸彈後容易被集火",
                "2 階 + 2 能量 + 棄能加傷，節奏慢過穿傷循環",
            ],
            "kill_lines": [
                "水忍蛙 200 + 黑夜魔靈特性 130 = 330，可打高端血量線",
            ],
            "tempo_note": "多龍通常較快開到穿傷；忍蛙要進化同填能先有完整輸出",
        },
    },
    {
        "schema_version": SCHEMA_VERSION,
        "user_archetype": "mega_greninja",
        "user_display_name": "Mega 水忍蛙／甲賀忍蛙",
        "opponent_archetype": "lucario",
        "opponent_display_name": "路卡",
        "verified": False,
        "source": "user_seed_2026-09-07",
        "setup": {
            "evolution_stage": "stage2",
            "energy_to_attack": 2,
            "energy_type": "Water",
            "boost_cost": "加傷要棄水能量",
            "search_filter_notes": "展開慢；被點傷後進入更多打擊帶",
        },
        "quirks": [
            {
                "id": "chip_opens_300_band",
                "rule": "含羞苞等小點傷可把 310 推進 300 帶",
                "applies_to": "active",
                "note": "斷點改變後路卡線嘅蛋白飲等工具會對上",
            }
        ],
        "breakpoints": [
            {
                "defender": "甲賀忍蛙／Mega 水忍蛙",
                "hp": 310,
                "modifier": "chip",
                "modifier_note": "含羞苞點到約 300",
                "effective_hp": 300,
                "killed_by": ["路卡 + 蛋白飲"],
                "not_killed_by": ["未標明嘅單發路卡招式（需對卡文核對）"],
            }
        ],
        "vs_archetype": {
            "advantages": [
                "太晶後排仍防招式穿傷",
            ],
            "disadvantages": [
                "310 原血已經尷尬；被點 10 之後進入 300 帶，路卡工具線變齊",
            ],
            "kill_lines": [
                "含羞苞把 310→300 後，路卡 + 蛋白飲可一刀",
            ],
            "tempo_note": "路卡爆發快過 2 階忍蛙開槍",
        },
    },
    {
        "schema_version": SCHEMA_VERSION,
        "user_archetype": "mega_greninja",
        "user_display_name": "Mega 水忍蛙／甲賀忍蛙",
        "opponent_archetype": "rika_grass",
        "opponent_display_name": "竹蘭草（竹蘭的羅絲雷朵）",
        "verified": False,
        "source": "user_seed_2026-09-07",
        "setup": {
            "evolution_stage": "stage2",
            "energy_to_attack": 2,
            "energy_type": "Water",
            "boost_cost": "加傷要棄水能量",
            "search_filter_notes": "第二招 120 打唔死 130 血羅絲雷朵",
        },
        "quirks": [
            {
                "id": "awkward_120_vs_130",
                "rule": "輸出數字低過對手引擎體 HP",
                "applies_to": "opponent",
                "note": "竹蘭的羅絲雷朵 130 HP，忍蛙 2 技能 120，清唔走引擎",
            }
        ],
        "breakpoints": [
            {
                "defender": "竹蘭的羅絲雷朵",
                "hp": 130,
                "modifier": "none",
                "modifier_note": "原血",
                "effective_hp": 130,
                "killed_by": [],
                "not_killed_by": ["忍蛙第二招 120"],
            },
            {
                "defender": "甲賀忍蛙／Mega 水忍蛙",
                "hp": 310,
                "modifier": "chip",
                "modifier_note": "含羞苞點到約 300",
                "effective_hp": 300,
                "killed_by": ["烈咬陸鯊 + 2 張竹蘭的羅絲雷朵"],
                "not_killed_by": [],
            },
        ],
        "vs_archetype": {
            "advantages": [
                "有 200 前排同 330 組合線時， theoretically 可壓過單隻引擎體",
            ],
            "disadvantages": [
                "120 打唔死 130，清場尷尬",
                "被點到 300 後，陸鯊 + 2 羅絲雷朵可一刀返斬 310 線",
            ],
            "kill_lines": [
                "對方：含羞苞 310→300，烈咬陸鯊 + 2 竹蘭羅絲雷朵斬忍蛙",
                "己方：第二招 120 斬唔死 130 羅絲雷朵",
            ],
            "tempo_note": "草線用點傷改斷點，忍蛙要用更高數字或組合線先划算",
        },
    },
]

# Every seed row above belongs to this single canonical archetype.
SEED_USER_ARCHETYPE = "greninja"

PLACEHOLDER_NOTE = (
    "手寫用戶種子（2026-09-07），未經卡文／卡庫核對，亦非 profile job 產生；"
    "只適用於 greninja／mega_greninja 呢一副，唔可以當成其他套牌嘅資料。"
)

# Canonical archetype keys -> aliases used by callers. Mirrors the family ids
# used by services.limitless_decks.meta_field so DB briefs can be matched.
ARCHETYPE_ALIASES: dict[str, str] = {
    "忍蛙": "greninja",
    "水忍蛙": "greninja",
    "甲賀忍蛙": "greninja",
    "mega水忍蛙": "greninja",
    "greninja": "greninja",
    "mega_greninja": "greninja",
    "frogadier": "greninja",
    "froakie": "greninja",
    "多龍": "dragapult",
    "多龍梅里亞": "dragapult",
    "多龍巴魯托": "dragapult",
    "多龍梅西亞": "dragapult",
    "多龍奇": "dragapult",
    "dragapult": "dragapult",
    "dreepy": "dragapult",
    "drakloak": "dragapult",
    "路卡": "lucario",
    "路卡利歐": "lucario",
    "lucario": "lucario",
    "riolu": "lucario",
    "竹蘭": "rika_grass",
    "竹蘭草": "rika_grass",
    "羅絲雷朵": "rika_grass",
    "rika": "rika_grass",
    "roserade": "rika_grass",
    "黑夜魔靈": "dusknoir",
    "夜巡靈": "dusknoir",
    "dusknoir": "dusknoir",
}

_VARIABLE_DAMAGE_RE = re.compile(r"[+xX×*\-−]")


def list_matchup_sheets() -> list[dict[str, Any]]:
    """Index of the hand-written seed sheets (all placeholders, verified=false)."""
    return [
        {
            "user_archetype": row["user_archetype"],
            "opponent_archetype": row["opponent_archetype"],
            "user_display_name": row.get("user_display_name"),
            "opponent_display_name": row.get("opponent_display_name"),
            "verified": False,
            "placeholder": True,
            "source": row.get("source"),
        }
        for row in SEED_SHEETS
    ]


def _norm(value: Any) -> str:
    return str(value or "").strip().lower().replace(" ", "").replace("／", "/")


def _canonical_archetype(value: Any) -> str:
    key = _norm(value)
    if not key:
        return ""
    return ARCHETYPE_ALIASES.get(key, key)


def _json_obj(value: Any) -> dict[str, Any]:
    """psycopg2 normally returns jsonb as dict; tolerate a raw JSON string too."""
    if isinstance(value, dict):
        return value
    if isinstance(value, str) and value.strip():
        try:
            import json

            parsed = json.loads(value)
            return parsed if isinstance(parsed, dict) else {}
        except Exception:
            return {}
    return {}


def _seed_placeholder_sheets(user_id: str, opp_id: str, opp_raw: str) -> list[dict[str, Any]]:
    """Return seeds ONLY for the one seeded archetype, clearly labelled."""
    rows: list[dict[str, Any]] = []
    for row in SEED_SHEETS:
        if _canonical_archetype(row.get("user_archetype")) != user_id:
            continue
        if opp_raw:
            if not opp_id or _canonical_archetype(row.get("opponent_archetype")) != opp_id:
                continue
        sheet = dict(row)
        sheet["verified"] = False
        sheet["placeholder"] = True
        sheet["placeholder_note"] = PLACEHOLDER_NOTE
        rows.append(sheet)
    return rows


def _load_briefs() -> tuple[list[dict[str, Any]], str | None]:
    """Read-only fetch of stored archetype briefs. Never creates or writes tables."""
    try:
        import database  # backend.database
    except Exception as exc:  # pragma: no cover - import environment dependent
        return [], f"database module unavailable: {exc}"

    conn = None
    try:
        conn = database.get_db_connection()
        if not conn:
            return [], "database unavailable"
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT combo_key, label, label_zh, last_seen_month, last_rank,
                   last_share, last_n, sample_deck_ids, profile, analysis
            FROM format_archetype_briefs
            ORDER BY last_seen_month DESC NULLS LAST, last_rank NULLS LAST
            """
        )
        return [dict(row) for row in cursor.fetchall() or []], None
    except Exception as exc:
        return [], f"format_archetype_briefs unavailable: {exc}"
    finally:
        if conn is not None:
            try:
                conn.rollback()
            except Exception:
                pass
            try:
                conn.close()
            except Exception:
                pass


def _brief_matches(brief: dict[str, Any], query: str) -> bool:
    if not query:
        return False
    combo_key = _norm(brief.get("combo_key"))
    if query == combo_key:
        return True
    if query in {part for part in combo_key.split("+") if part}:
        return True
    if query in _norm(brief.get("label")) or query in _norm(brief.get("label_zh")):
        return True
    profile = _json_obj(brief.get("profile"))
    for family in profile.get("families") or []:
        if isinstance(family, dict) and query == _norm(family.get("id")):
            return True
    return False


def _find_brief(briefs: list[dict[str, Any]], raw: str) -> dict[str, Any] | None:
    query = _norm(raw)
    if not query:
        return None
    for brief in briefs:
        if _brief_matches(brief, query):
            return brief
    return None


def _profile_facts(brief: dict[str, Any]) -> dict[str, Any]:
    profile = _json_obj(brief.get("profile"))
    sample_ids = brief.get("sample_deck_ids")
    if isinstance(sample_ids, str):
        try:
            import json

            sample_ids = json.loads(sample_ids)
        except Exception:
            sample_ids = []
    return {
        "combo_key": brief.get("combo_key"),
        "label": brief.get("label"),
        "label_zh": brief.get("label_zh"),
        "last_seen_month": brief.get("last_seen_month"),
        "sample_deck_count": len(sample_ids or []) if isinstance(sample_ids, list) else 0,
        "families": profile.get("families") or [],
        "hp_table": profile.get("hp_table") or [],
        "pokemon_kits": profile.get("pokemon_kits") or [],
        "skill_catalog": profile.get("skill_catalog") or [],
    }


def _collect_attacks(profile: dict[str, Any]) -> list[dict[str, Any]]:
    """Flatten stored printed attacks; mark which ones are safe fixed-damage."""
    attacks: list[dict[str, Any]] = []
    seen = set()
    for kit in profile.get("pokemon_kits") or []:
        if not isinstance(kit, dict):
            continue
        attacker = kit.get("name") or kit.get("card_id") or "?"
        for attack in kit.get("attacks") or []:
            if not isinstance(attack, dict):
                continue
            raw = str(attack.get("damage") or "").strip()
            value = attack.get("damage_value")
            try:
                value = int(value)
            except (TypeError, ValueError):
                value = None
            effect = str(attack.get("effect") or "").strip()
            fixed = bool(value) and not _VARIABLE_DAMAGE_RE.search(raw) and not effect
            key = (attacker, attack.get("name"), raw)
            if key in seen:
                continue
            seen.add(key)
            attacks.append(
                {
                    "attacker": attacker,
                    "name": attack.get("name") or "",
                    "damage": raw,
                    "damage_value": value,
                    "fixed": fixed,
                    "effect": effect,
                }
            )
    return attacks


def _printed_breakpoints(user_profile: dict[str, Any], opp_profile: dict[str, Any]) -> list[dict[str, Any]]:
    """Strictly mechanical printed-damage vs stored-HP comparison.

    ``killed_by`` is only filled for attacks with fixed printed damage and no
    effect text, so ``damage >= hp`` is a sound lower-bound claim.
    ``not_killed_by`` is only filled when EVERY parsed attack is fixed damage.
    """
    attacks = _collect_attacks(user_profile)
    all_fixed = bool(attacks) and all(a["fixed"] for a in attacks)
    defenders = [
        row
        for row in (opp_profile.get("hp_table") or [])
        if isinstance(row, dict) and isinstance(row.get("hp"), int) and row["hp"] > 0
    ]
    breakpoints: list[dict[str, Any]] = []
    for defender in defenders:
        hp = int(defender["hp"])
        killed = [a for a in attacks if a["fixed"] and a["damage_value"] >= hp]
        breakpoints.append(
            {
                "defender": defender.get("name") or defender.get("card_id") or "?",
                "hp": hp,
                "modifier": "none",
                "modifier_note": "純印刷招式傷害對存庫 HP；未計弱點／抗性／道具／特性／跨卡特攻",
                "effective_hp": hp,
                "killed_by": [
                    f"{a['attacker']}｜{a['name']} {a['damage']}".strip() for a in killed
                ],
                "not_killed_by": (
                    [
                        f"{a['attacker']}｜{a['name']} {a['damage']}".strip()
                        for a in attacks
                        if a["fixed"] and a["damage_value"] < hp
                    ]
                    if all_fixed
                    else []
                ),
                "method": "printed_damage_vs_hp",
                "verified": False,
            }
        )
    return breakpoints


def _derive_sheet(user_brief: dict[str, Any], opp_brief: dict[str, Any] | None) -> dict[str, Any]:
    user_profile = _json_obj(user_brief.get("profile"))
    opp_profile = _json_obj(opp_brief.get("profile")) if opp_brief else {}
    breakpoints = _printed_breakpoints(user_profile, opp_profile) if opp_brief else []
    limitations = [
        "由 format_archetype_briefs 存庫 profile 即場讀取，未對過卡文，verified=false。",
        "breakpoints 只比較印刷招式傷害同存庫 HP，未計弱點／抗性／道具／特性／點傷／跨卡組合。",
        "setup／quirks／advantages／kill_lines 屬判斷內容，本 builder 唔會生成。",
    ]
    if opp_brief is None:
        limitations.append("未提供或未收錄對手 archetype，只回用戶套 profile 事實。")
    return {
        "schema_version": SCHEMA_VERSION,
        "user_archetype": user_brief.get("combo_key"),
        "user_display_name": user_brief.get("label_zh") or user_brief.get("label"),
        "opponent_archetype": (opp_brief or {}).get("combo_key"),
        "opponent_display_name": (opp_brief or {}).get("label_zh") or (opp_brief or {}).get("label"),
        "verified": False,
        "placeholder": False,
        "derived": True,
        "source": "db:format_archetype_briefs",
        "setup": {},
        "quirks": [],
        "breakpoints": breakpoints,
        "vs_archetype": {
            "advantages": [],
            "disadvantages": [],
            "kill_lines": [],
            "tempo_note": None,
        },
        "profile_facts": {
            "user": _profile_facts(user_brief),
            "opponent": _profile_facts(opp_brief) if opp_brief else None,
        },
        "limitations": limitations,
    }


def get_matchup_sheet(user_archetype: str = "", opponent_archetype: str = "") -> dict[str, Any]:
    """Build a matchup sheet for a CONCRETE archetype key, or report no data.

    ``user_archetype`` is required. There is no default archetype: a blank or
    unknown key returns ``available=False`` with a reason instead of returning
    another archetype's sheet. Hand-written seeds are returned only when the
    requested key is exactly the one seeded archetype (greninja). Otherwise a
    read-only derivation from ``format_archetype_briefs`` is attempted.
    """
    user_raw = str(user_archetype or "").strip()
    opp_raw = str(opponent_archetype or "").strip()
    user_id = _canonical_archetype(user_raw)
    opp_id = _canonical_archetype(opp_raw)

    result: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "schema": MATCHUP_SHEET_SCHEMA,
        "profile_schema": ARCHETYPE_PROFILE_SCHEMA,
        "generation": dict(GENERATION_NOTES),
        "user_archetype_key": user_id,
        "opponent_archetype_key": opp_id,
        "available": False,
        "reason": "",
        "count": 0,
        "matchups": [],
        "sheets": [],  # backward-compatible alias of `matchups`
        "available_sheets": list_matchup_sheets(),
        "note": "",
    }

    if not user_raw or not user_id:
        result["reason"] = "missing_user_archetype"
        result["note"] = (
            "get_matchup_sheet 需要具體 user_archetype；"
            "唔會再默認代入 mega_greninja 或者其他套牌。"
        )
        return result

    # Real stored profile data wins; hand-written seeds are only a last resort.
    briefs, db_reason = _load_briefs()
    user_brief = _find_brief(briefs, user_raw) if not db_reason else None
    if user_brief:
        opp_brief = _find_brief(briefs, opp_raw) if opp_raw else None
        sheets = [_derive_sheet(user_brief, opp_brief)]
        result["available"] = True
        result["reason"] = "derived_from_db_profile"
        result["count"] = len(sheets)
        result["matchups"] = sheets
        result["sheets"] = sheets
        result["note"] = (
            "由 format_archetype_briefs 存庫 profile 唯讀推導；verified=false，"
            "breakpoints 只計印刷傷害對 HP。"
        )
        if opp_raw and not opp_brief:
            result["note"] += f" 對手 '{opp_raw}' 未收錄，未提供對局斷點。"
        return result

    seeded = _seed_placeholder_sheets(user_id, opp_id, opp_raw)
    if seeded:
        result["available"] = True
        result["reason"] = "seed_placeholder"
        result["count"] = len(seeded)
        result["matchups"] = seeded
        result["sheets"] = seeded
        result["note"] = (
            "只有 greninja／mega_greninja 嘅手寫種子；全部 verified=false，"
            "係 placeholder，唔係卡庫或 profile job 產生。"
        )
        return result

    if db_reason:
        result["reason"] = "no_profile_data"
        result["note"] = f"無真實 archetype profile 可用：{db_reason}"
        return result

    result["reason"] = "no_profile_data_for_archetype"
    result["note"] = (
        f"format_archetype_briefs 無 user_archetype='{user_raw}' 嘅 profile；"
        "唔會用其他套牌數據代替。"
    )
    return result
